### PR TITLE
provision-testenv: testenv deploying in pipeline

### PR DESCRIPTION
**Pull request by sodar**
- Deploy test environment in main pipeline
- Lock on data plane network for each test
- Refactor {deploy,destroy}-demo-env to use the code for test environment deployment

A few notes:
- `testbeds` variable just stores test env hostnames and IPs; it will be used in future PRs to deploy artifacts
- If pipeline is aborted while templates are deployed, cleanup does not work properly. pyvmomi does not cancel running tasks in VMware.

### CODE REVIEW

**Comment by kaweue** [comment]
recheck no bug

**Comment by jablonskim** [comment]
recheck no bug

**Review by wurbanski — DISMISSED** [review]
Looks good. 
I only suggest getting rid of `script` clauses in pipeline if possible.

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Comment by sodar** [comment]
recheck no bug

**Review by jablonskim — APPROVED** [review]

**Comment by sodar** [comment]
recheck no bug

**Pull request merged**
