### PR TITLE
JW-1403 : Use dep prune to make sure that we are not using GPL code.

### PR DESCRIPTION
**Pull request by kaweue**

### CODE REVIEW

**Comment by kaweue** [comment]
It is working: http://10.84.12.26:8080/job/WinContrail/job/WinCI-pm-test/8/

**Review by krdln — CHANGES_REQUESTED** [review]
Please split it into two `Invoke-NativeCommand` to make error location more precise. `Invoke-NativeCommand` should be only used to run single command.

**Comment by kaweue** [comment]
recheck no bug

**Comment by kaweue** [comment]
recheck no bug

**Review by krdln — APPROVED** [review]

**Review by katrybacka — APPROVED** [review]

**Comment by kaweue** [comment]
It works http://10.84.12.26:8080/job/WinContrail/job/WinCI-pm-test/29/console

**Pull request merged**
