### PR TITLE
Windows jobs should be voting

### PR DESCRIPTION
**Pull request by kaweue**

### CODE REVIEW

**Review by m-kostrzewa — APPROVED** [review]

**Review by katrybacka — APPROVED** [review]

**Comment by kaweue** [comment]
recheck no bug

**Comment by kaweue** [comment]
recheck no bug

**Comment by kaweue** [comment]
recheck no bug

**Comment by kaweue** [comment]
recheck no bug

**Comment by kaweue** [comment]
recheck no bug

**Pull request merged**
