### PR TITLE
JW-1400 Add deleteDir step to build stage

### PR DESCRIPTION
**Pull request by krdln**
This should fix `src/github.com/codilime/contrail-windows-docker' already exists and is not an empty directory`

Note: Every step that uses powershell scripts probably needs `deleteDir`, doing it for purely ansible steps is not needed.

### CODE REVIEW

**Comment by krdln** [comment]
[Logs](http://10.84.12.26:8080/job/WinContrail/job/winci-server2016-mkrmkr/52/console)

**Review by jacek-izykowski — APPROVED** [review]
4D-distributed pair review with deferred pair assignment

**Comment by krdln** [comment]
This answer *may* explain why the workspace itself is not removed by `currentDir`: https://stackoverflow.com/a/44950899

**Review by wurbanski — APPROVED** [review]
Simple, yet elegant solution.

**Pull request merged**
